<a href="https://colab.research.google.com/github/kla55/Pytorch_learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## 00.Pytorch Fundamental

# Resource notebook: mrdbourke

In [ ]:
!nvidia-smi

Tue Sep 26 01:28:35 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to tenors
A way to represents the numeric data and they represent something else.

First tensor is called Scalar

In [ ]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# Number of Dimensions
scaler.ndim

0

In [ ]:
# get tensor back as Python int
scaler.item()

7

In [ ]:
# Vector - which has magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# number of closed square brackets
vector.ndim

1

In [ ]:
# number of items im the bracket 2 by 1 element
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
# we have 1, 3 by 3 tensor
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

Why random tensors? They are important because the way NN learns is that they start with tensor full of random numbers than adjust those numbers to better represent the data.

Start with random number > look at data > update random numbers > look at data update with numbers

In [ ]:
random_tensor = torch.rand(2,3,4)

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([2, 3, 4])

In [ ]:
random_tensor

tensor([[[0.7237, 0.0090, 0.3289, 0.1957],
         [0.0774, 0.2464, 0.4869, 0.2819],
         [0.7690, 0.1691, 0.4763, 0.8124]],

        [[0.1155, 0.7816, 0.9642, 0.4310],
         [0.2189, 0.3822, 0.7002, 0.9618],
         [0.2297, 0.3437, 0.0830, 0.2792]]])

In [ ]:
# create a randome image tensor
random_image_size_tensor = torch.rand(224,224,3)

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor

tensor([[[0.4230, 0.3167, 0.0417],
         [0.1907, 0.0095, 0.7754],
         [0.3368, 0.2665, 0.3851],
         ...,
         [0.9632, 0.1247, 0.7375],
         [0.6933, 0.7136, 0.4375],
         [0.5421, 0.0932, 0.3452]],

        [[0.9237, 0.5279, 0.7831],
         [0.8575, 0.9363, 0.5603],
         [0.9185, 0.5820, 0.7015],
         ...,
         [0.0110, 0.0414, 0.3820],
         [0.4024, 0.9346, 0.6584],
         [0.9837, 0.9134, 0.5130]],

        [[0.6275, 0.6427, 0.4496],
         [0.1593, 0.4899, 0.1910],
         [0.5365, 0.5326, 0.3060],
         ...,
         [0.6500, 0.4063, 0.9865],
         [0.7374, 0.4503, 0.4895],
         [0.1349, 0.8967, 0.5300]],

        ...,

        [[0.0262, 0.9268, 0.9274],
         [0.5761, 0.9017, 0.8541],
         [0.1331, 0.6627, 0.2033],
         ...,
         [0.2032, 0.7964, 0.0062],
         [0.7154, 0.4912, 0.7367],
         [0.0621, 0.5347, 0.3936]],

        [[0.2112, 0.3429, 0.8502],
         [0.5063, 0.0547, 0.3563],
         [0.

# Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Create a range of tensors and tensor-like

In [ ]:
torch.range(0,10)

<ipython-input-29-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
torch.arange(0,900, step=87)

tensor([  0,  87, 174, 261, 348, 435, 522, 609, 696, 783, 870])

In [ ]:
# Create tenor like
one_to_ten = torch.zeros_like(input=torch.arange(0,900, step=87))

In [ ]:
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [ ]:
float32_tensor = torch.tensor([3,6,9], dtype = torch.float32)

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float32_tensor = torch.tensor([3.9,6.9,9.9],
                              dtype = torch.int16, # datatype is tensor
                              device = 'cpu', # device is cpu by default can also be cuda
                              requires_grad=False)# pytorch to track the gradient for certain calcualtions
float32_tensor

tensor([3, 6, 9], dtype=torch.int16)

In [ ]:
float_16_tensor = float32_tensor.type(torch.int16)

In [ ]:
float_16_tensor * float32_tensor

tensor([ 9, 36, 81], dtype=torch.int16)

In [ ]:
# so what this does is that even if the dtypes are different for float and int,
# it works but usually if tensors are in the wrong datatype it would not run

# overall this is just learning and getting information from tensors
# typical tensor information

'''
ndim
tensor.dtype
tensor.shape
tensor.device
'''

'\nndim\ntensor.dtype\ntensor.shape\ntensor.device\n'

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7716, 0.8626, 0.1006, 0.6060],
        [0.2831, 0.6897, 0.5933, 0.6648],
        [0.2167, 0.1801, 0.0346, 0.1050]])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
print(some_tensor.shape,
      some_tensor.device,
      some_tensor.size())

torch.Size([3, 4]) cpu torch.Size([3, 4])


# Manipulating tensors

In [ ]:
'''
tensor operation
addition
subtraction
multiplication
division
matrix multiplication
'''

'\ntensor operation\naddition\nsubtraction\nmultiplication\ndivision\nmatrix multiplication\n'

In [ ]:
st = torch.tensor([1,3,4])
st + 10

tensor([11, 13, 14])

In [ ]:
st * 10

tensor([10, 30, 40])

In [ ]:
st / 10

tensor([0.1000, 0.3000, 0.4000])

In [ ]:
st * torch.rand(1,3)

tensor([[0.3509, 2.4809, 1.7651]])

In [ ]:
torch.mul(st, 9)

tensor([ 9, 27, 36])

In [ ]:
torch.add(st, 19)

tensor([20, 22, 23])

In [ ]:
# Matrix multiplication or dot product
%%time
torch.matmul(st, st) # which is 1*1 + 3*3 + 4*4 = 1 + 9 + 16 = 26

CPU times: user 366 µs, sys: 18 µs, total: 384 µs
Wall time: 299 µs


tensor(26)

In [ ]:
%%time
value = 0
for i in range(len(st)):
  value = st[i] * st[i] + value
print(value)

tensor(26)
CPU times: user 2.5 ms, sys: 0 ns, total: 2.5 ms
Wall time: 2.28 ms


In [ ]:
# there are two rules to form matrix mul that need to satisfy
# 1 inner dimensions must match - (3,2) @ (3,2) won't work
# (3,2) @ (2,3) will work

torch.matmul(torch.rand(3,2),torch.rand(3,2)) # inner dimensions do not match


RuntimeError: ignored

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # will work
# also the results of the matrix has the shape of the outer dimensions

tensor([[0.5991, 1.1701, 0.5699],
        [0.1795, 0.4108, 0.2615],
        [0.5697, 1.0850, 0.5003]])

# One of the most commen errors in deep learning: shape errors

In [ ]:
tens_a = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tens_b = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tens_c = torch.tensor([[1,2,3],
                      [3,4, 5]])

In [ ]:
tens_a.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(tens_a, tens_b)

RuntimeError: ignored

In [ ]:
# can also use mm instead of matmul
torch.mm(tens_a, tens_c)

tensor([[ 7, 10, 13],
        [15, 22, 29],
        [23, 34, 45]])

In [ ]:
# to fix our tensor shape issue we can manipulate our shape of our tensor using transpose
tens_b_t = tens_b.T
tens_b_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [ ]:
torch.mm(tens_b_t, tens_a)

tensor([[35, 44],
        [44, 56]])

In [ ]:
torch.mm(tens_b_t, tens_a).shape

torch.Size([2, 2])