<a href="https://colab.research.google.com/github/kla55/Pytorch_learning/blob/main/Pytorch_youtube/FreeCodeAcademy/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 00.Pytorch Fundamental

# Resource notebook: mrdbourke

In [2]:
!nvidia-smi

Thu Sep 28 00:35:05 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to tenors
A way to represents the numeric data and they represent something else.

First tensor is called Scalar

In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
# Number of Dimensions
scaler.ndim

0

In [6]:
# get tensor back as Python int
scaler.item()

7

In [7]:
# Vector - which has magnitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
# number of closed square brackets
vector.ndim

1

In [9]:
# number of items im the bracket 2 by 1 element
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
# we have 1, 3 by 3 tensor
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

Why random tensors? They are important because the way NN learns is that they start with tensor full of random numbers than adjust those numbers to better represent the data.

Start with random number > look at data > update random numbers > look at data update with numbers

In [18]:
random_tensor = torch.rand(2,3,4)

In [19]:
random_tensor.ndim

3

In [20]:
random_tensor.shape

torch.Size([2, 3, 4])

In [21]:
random_tensor

tensor([[[0.2106, 0.2993, 0.8010, 0.6234],
         [0.8064, 0.6475, 0.7205, 0.7901],
         [0.1422, 0.6637, 0.6051, 0.9626]],

        [[0.1534, 0.9652, 0.9460, 0.0173],
         [0.4278, 0.6868, 0.1556, 0.8954],
         [0.7272, 0.5696, 0.3489, 0.9238]]])

In [22]:
# create a randome image tensor
random_image_size_tensor = torch.rand(224,224,3)

In [23]:
random_image_size_tensor.ndim

3

In [24]:
random_image_size_tensor

tensor([[[0.6201, 0.1112, 0.9889],
         [0.2764, 0.9833, 0.6290],
         [0.7694, 0.8959, 0.8057],
         ...,
         [0.8548, 0.3596, 0.6088],
         [0.3641, 0.1774, 0.5639],
         [0.3919, 0.8591, 0.2722]],

        [[0.0242, 0.5770, 0.4523],
         [0.0783, 0.2156, 0.9586],
         [0.2750, 0.1841, 0.1039],
         ...,
         [0.4976, 0.6650, 0.8437],
         [0.1378, 0.8565, 0.4340],
         [0.3918, 0.6770, 0.1399]],

        [[0.5974, 0.1522, 0.9295],
         [0.2779, 0.9247, 0.5419],
         [0.3638, 0.1257, 0.2305],
         ...,
         [0.2947, 0.9899, 0.4143],
         [0.9748, 0.3242, 0.0489],
         [0.6837, 0.7011, 0.9894]],

        ...,

        [[0.8840, 0.8272, 0.5445],
         [0.3202, 0.3179, 0.4327],
         [0.1232, 0.1991, 0.7490],
         ...,
         [0.8562, 0.3147, 0.6663],
         [0.8355, 0.1717, 0.5008],
         [0.6387, 0.8519, 0.8600]],

        [[0.5889, 0.0079, 0.4348],
         [0.5345, 0.8118, 0.5361],
         [0.

# Zeros and ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros.dtype

torch.float32

In [27]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Create a range of tensors and tensor-like

In [28]:
torch.range(0,10)

<ipython-input-28-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
torch.__version__

'2.0.1+cu118'

In [30]:
torch.arange(0,900, step=87)

tensor([  0,  87, 174, 261, 348, 435, 522, 609, 696, 783, 870])

In [31]:
# Create tenor like
one_to_ten = torch.zeros_like(input=torch.arange(0,900, step=87))

In [32]:
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [33]:
float32_tensor = torch.tensor([3,6,9], dtype = torch.float32)

In [34]:
float32_tensor.dtype

torch.float32

In [35]:
float32_tensor = torch.tensor([3.9,6.9,9.9],
                              dtype = torch.int16, # datatype is tensor
                              device = 'cpu', # device is cpu by default can also be cuda
                              requires_grad=False)# pytorch to track the gradient for certain calcualtions
float32_tensor

tensor([3, 6, 9], dtype=torch.int16)

In [36]:
float_16_tensor = float32_tensor.type(torch.int16)

In [37]:
float_16_tensor * float32_tensor

tensor([ 9, 36, 81], dtype=torch.int16)

In [38]:
# so what this does is that even if the dtypes are different for float and int,
# it works but usually if tensors are in the wrong datatype it would not run

# overall this is just learning and getting information from tensors
# typical tensor information

'''
ndim
tensor.dtype
tensor.shape
tensor.device
'''

'\nndim\ntensor.dtype\ntensor.shape\ntensor.device\n'

In [39]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5522, 0.5788, 0.3008, 0.2033],
        [0.1324, 0.0590, 0.5495, 0.3721],
        [0.4423, 0.5678, 0.3449, 0.4228]])

In [40]:
some_tensor.dtype

torch.float32

In [41]:
print(some_tensor.shape,
      some_tensor.device,
      some_tensor.size())

torch.Size([3, 4]) cpu torch.Size([3, 4])


# Manipulating tensors

In [42]:
'''
tensor operation
addition
subtraction
multiplication
division
matrix multiplication
'''

'\ntensor operation\naddition\nsubtraction\nmultiplication\ndivision\nmatrix multiplication\n'

In [43]:
st = torch.tensor([1,3,4])
st + 10

tensor([11, 13, 14])

In [44]:
st * 10

tensor([10, 30, 40])

In [45]:
st / 10

tensor([0.1000, 0.3000, 0.4000])

In [46]:
st * torch.rand(1,3)

tensor([[0.8612, 1.6889, 0.9659]])

In [47]:
torch.mul(st, 9)

tensor([ 9, 27, 36])

In [48]:
torch.add(st, 19)

tensor([20, 22, 23])

In [49]:
# Matrix multiplication or dot product
%%time
torch.matmul(st, st) # which is 1*1 + 3*3 + 4*4 = 1 + 9 + 16 = 26

CPU times: user 1.19 ms, sys: 32 µs, total: 1.22 ms
Wall time: 3.07 ms


tensor(26)

In [50]:
%%time
value = 0
for i in range(len(st)):
  value = st[i] * st[i] + value
print(value)

tensor(26)
CPU times: user 449 µs, sys: 0 ns, total: 449 µs
Wall time: 455 µs


In [51]:
# there are two rules to form matrix mul that need to satisfy
# 1 inner dimensions must match - (3,2) @ (3,2) won't work
# (3,2) @ (2,3) will work

torch.matmul(torch.rand(3,2),torch.rand(3,2)) # inner dimensions do not match


RuntimeError: ignored

In [52]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # will work
# also the results of the matrix has the shape of the outer dimensions

tensor([[1.1183, 1.0550, 0.5101],
        [0.5162, 0.5143, 0.2050],
        [0.4616, 0.4716, 0.1703]])

# One of the most common errors in deep learning: shape errors

In [53]:
tens_a = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tens_b = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])

tens_c = torch.tensor([[1,2,3],
                      [3,4, 5]])

In [54]:
tens_a.shape

torch.Size([3, 2])

In [55]:
torch.matmul(tens_a, tens_b)

RuntimeError: ignored

In [56]:
# can also use mm instead of matmul
torch.mm(tens_a, tens_c)

tensor([[ 7, 10, 13],
        [15, 22, 29],
        [23, 34, 45]])

In [57]:
# to fix our tensor shape issue we can manipulate our shape of our tensor using transpose
tens_b_t = tens_b.T
tens_b_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [58]:
torch.mm(tens_b_t, tens_a)

tensor([[35, 44],
        [44, 56]])

In [59]:
torch.mm(tens_b_t, tens_a).shape

torch.Size([2, 2])

# 23. Finding the min, max, mean & sum

In [64]:
x = torch.arange(0,100,3)
x

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
        54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [65]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [66]:
torch.max(x), x.max()

(tensor(99), tensor(99))

In [68]:
torch.mean(x) # not the right datatype, it requires a tensor of float32 datatype and shape issues

RuntimeError: ignored

In [69]:
x.dtype

torch.int64

In [70]:
x1 = x.type(torch.float32)
x1.mean()

tensor(49.5000)

In [71]:
torch.mean(x1)

tensor(49.5000)

In [73]:
torch.sum(x1), x.sum()

(tensor(1683.), tensor(1683))

# Finding indexes

In [76]:
# returns index of the tensor position
torch.argmin(x1), torch.argmax(x1)

(tensor(0), tensor(33))

In [77]:
x1

tensor([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
        42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78., 81.,
        84., 87., 90., 93., 96., 99.])

In [78]:
x1[1]

tensor(3.)

In [79]:
x[10]

tensor(30)

 # 25. Reshaping, viewing and stacking

reshape - reshape an input tensor to a defined shape

view - return a view of the input tensor of a certain shape but keep the same memory of original tensor

stacking - combine multiple tensor on top of each other vstack / torch.hstack

squeeze - remove all 1 dimensions from a tensor

unsqeeze - add 1 dimension to a target tensor

permute - return a view of the input with the dimension permuted in a certain way

In [1]:
import torch
x = torch.arange(1,10,1)

In [2]:
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [3]:
x_reshape = x.reshape(1,3, 3)
x_reshape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
x_reshape = x.reshape(9,1)
x_reshape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [5]:
# changing z changes x because a view of tensor shares the same memory as the input
z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [6]:
z[:,0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [7]:
# stack tensors on top of each other
x1 = torch.stack([x,x,x,x], dim = 0)
x1

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
torch.vstack([x,x,x])

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
torch.hstack([x,x,x])

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9])

26. Squeezing, unsqueezing and permuting

In [10]:
# removes all single dimensions from a target tensor
print(z.squeeze())
print(z.squeeze().shape)

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])


In [11]:
print(z)
print(z.shape)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])


In [12]:
# adds a single dimension to a target tensor at a specfic dim
z.unsqueeze(1)

tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [13]:
print(f"Previous tensor: {z}")
print(f"Previous shape: {z.shape}")

# Remove extra dimension from x_reshaped
z1 = z.squeeze()
print(f"\nNew tensor: {z1}")
print(f"New shape: {z1.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [14]:
print(f"Previous tensor: {z}")
print(f"Previous shape: {z.shape}")

## Add an extra dimension with unsqueeze
z2 = z.unsqueeze(dim=2) # dims is based on the index
print(f"\nNew tensor: {z2}")
print(f"New shape: {z2.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])
New shape: torch.Size([1, 9, 1])


In [15]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 25, 3))

# Permute the original tensor to rearrange the axis order - essentially swapping
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 25, 3])
New shape: torch.Size([3, 224, 25])


# 27. Selecting data (indexing)

Indexing is similar to Numpy

In [16]:
import torch

In [21]:
x = torch.arange(2,20,2).reshape(1,3,3)

In [22]:
x, x.shape

(tensor([[[ 2,  4,  6],
          [ 8, 10, 12],
          [14, 16, 18]]]),
 torch.Size([1, 3, 3]))

In [23]:
x[0]

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [24]:
x[0][1]

tensor([ 8, 10, 12])

In [25]:
x[0][1][1]

tensor(10)

In [26]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[2, 4, 6]])

In [27]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]


tensor([[ 4, 10, 16]])

In [28]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([10])

In [29]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([2, 4, 6])

# 28. PyTorch and NumPy


In [30]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))