<a href="https://colab.research.google.com/github/kla55/Pytorch_learning/blob/main/Pytorch_youtube/FreeCodeAcademy/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on torch.Tensor.
* The documentation on torch.cuda.

### 2. Create a random tensor with shape (7, 7).

In [15]:
import torch

In [16]:
t1 = torch.rand(7,7)
t1

tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
        [0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057],
        [0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [17]:
t2 = torch.rand(1,7)

In [18]:
torch.matmul(t1, t2.T)

tensor([[1.0466],
        [1.0884],
        [0.9919],
        [0.6820],
        [0.9108],
        [1.0100],
        [0.8004]])

# 4. Set the random seed to 0 and do 2 & 3 over again.

In [19]:
import random

In [20]:
rs = 42
torch.manual_seed(rs)
x3 = torch.rand(7,7)

torch.manual_seed(rs)
x4 = torch.rand(7,7)

In [21]:
print(x3)
print(x4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])


In [22]:
x3 == x4

tensor([[True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True]])

In [23]:
torch.matmul(x4, x3)

tensor([[3.0938, 2.7098, 2.7137, 2.4572, 2.0022, 2.6702, 1.5846],
        [3.3895, 2.9893, 3.1231, 2.5021, 2.4269, 2.9460, 1.9052],
        [2.7491, 2.2521, 2.6359, 2.1248, 1.5986, 2.2926, 1.3090],
        [1.8673, 1.4693, 1.7706, 1.4647, 1.1175, 1.5853, 0.8991],
        [2.4226, 1.5995, 2.7522, 1.5699, 1.7422, 2.0439, 1.1817],
        [3.0465, 2.5504, 2.8351, 2.3736, 1.8572, 2.5716, 1.5115],
        [3.5308, 3.0218, 3.2089, 2.6470, 2.6204, 3.1240, 2.0379]])

# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [24]:
torch.cuda.is_available()

False

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Move tensor to GPU (if available)
torch.manual_seed(1234)
tensor = torch.rand(2,3)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [10]:
torch.manual_seed(12345)
tensor = torch.rand(2,2)
tensor_on_gpu1 = tensor.to(device)
tensor_on_gpu1

tensor([[0.9817, 0.8796],
        [0.9921, 0.4611]], device='cuda:0')

In [13]:
x5 = torch.matmul(tensor_on_gpu1, tensor_on_gpu)
x5

tensor([[1.3693, 0.9367, 1.1310],
        [1.1866, 0.9111, 1.0666]], device='cuda:0')

# 8. Find the maximum and minimum values of the output of 7.

In [21]:
x6 = torch.rand(2,8)
x6_tensor_gpu = x6.to(device)
print(x6_tensor_gpu)


print(x6[0].max())
print(x6[1].min())

tensor([[0.4976, 0.8073, 0.0570, 0.1124, 0.4085, 0.0044, 0.5679, 0.1460],
        [0.0512, 0.2969, 0.2321, 0.4974, 0.8351, 0.3782, 0.5995, 0.7259]],
       device='cuda:0')
tensor(0.8073)
tensor(0.0512)


In [22]:
print(torch.argmin(x6))
print(torch.argmax(x6))

tensor(5)
tensor(12)


# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [41]:
# Set seed
random_seed = 1


# Create random tensor
x10 = torch.rand(1,2,3,10)
print(x10, x10.shape)
# Remove single dimensions
x11 = x10.squeeze()
print(x11, x11.shape)
# Print out tensors and their shapes


tensor([[[[0.1041, 0.2280, 0.8485, 0.6139, 0.1944, 0.7805, 0.7996, 0.8769,
           0.6012, 0.7412],
          [0.1063, 0.2787, 0.6082, 0.5024, 0.3549, 0.3679, 0.3155, 0.8677,
           0.2898, 0.8331],
          [0.0681, 0.6789, 0.0883, 0.6627, 0.2596, 0.8588, 0.1166, 0.9973,
           0.9586, 0.6843]],

         [[0.9813, 0.0216, 0.4806, 0.0933, 0.8174, 0.4458, 0.7935, 0.3980,
           0.7111, 0.8914],
          [0.1505, 0.9581, 0.0098, 0.4619, 0.3816, 0.3493, 0.9959, 0.1873,
           0.5190, 0.5262],
          [0.6771, 0.3853, 0.8833, 0.9625, 0.2096, 0.3479, 0.1446, 0.7914,
           0.0367, 0.3327]]]]) torch.Size([1, 2, 3, 10])
tensor([[[0.1041, 0.2280, 0.8485, 0.6139, 0.1944, 0.7805, 0.7996, 0.8769,
          0.6012, 0.7412],
         [0.1063, 0.2787, 0.6082, 0.5024, 0.3549, 0.3679, 0.3155, 0.8677,
          0.2898, 0.8331],
         [0.0681, 0.6789, 0.0883, 0.6627, 0.2596, 0.8588, 0.1166, 0.9973,
          0.9586, 0.6843]],

        [[0.9813, 0.0216, 0.4806, 0.0933, 0.81